### ISSUE TITLE
How do i host this?

### ISSUE THREAD

**Issue by MrNicck** [blazsmaster/discord-gen-bot#5]
Right, so whenever i try to open index.js with node it just opens node and closes right after and then nothing happens. Help.

**Comment by blazsmaster** [comment]
Is that what you tried?
![image](https://user-images.githubusercontent.com/64538277/147856254-4b19eba4-e278-421c-abd4-059511c7adc2.png)
Install npm packages (`npm install`) then run index.js `node index.js`

**Comment by MrNicck** [comment]
no, how do i execute from the folder? cuz like i cant just execute index.js directly from a powershell window

**Comment by MrNicck** [comment]
like how do i get the powershell thing to know that its in that folder

**Comment by MrNicck** [comment]
![image](https://user-images.githubusercontent.com/85575533/147856647-1f09971f-f9bc-4d15-87da-a59426a287cc.png)
am i supposed to make a discord.js file or is it missing?

**Comment by blazsmaster** [comment]
Discord.js is a npm module. If you execute `npm install` in terminal you install every package from the package.json file. Maybe you can try this with manual installion: `npm install discord.js@12.5.3`

**Comment by MrNicck** [comment]
is there any way that i can make it only respond to a specific role?

**Comment by blazsmaster** [comment]
> is there any way that i can make it only respond to a specific role?

Yes. If you want I can write it.

**Comment by MrNicck** [comment]
yea! that'd be great. So if you have time and want to do it it would be great if you could make it so theres and admin role and a role that you need to gen so like the admin role would allow you to add stock n stuff if it makes sense.

**Comment by blazsmaster** [comment]
> yea! that'd be great. So if you have time and want to do it it would be great if you could make it so theres and admin role and a role that you need to gen so like the admin role would allow you to add stock n stuff if it makes sense.

Okay. Can I get your discord username and tag?

**Comment by MrNicck** [comment]
sure thing :)
Nicck#9776
