### ISSUE TITLE
not responfing

### ISSUE THREAD

**Issue by herobrine00100** [blazsmaster/discord-gen-bot#6]
**Describe the bug**

**To Reproduce**
![Screenshot (231)](https://user-images.githubusercontent.com/78717831/150514017-28eb4eb7-a28f-4b8a-83c8-a1655b051535.png)

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by blazsmaster** [comment]
Hello! I checked your error. The bot does not have send messages or send embed links permission on the channel where you executed the command.
![image](https://user-images.githubusercontent.com/64538277/152650950-acaed838-97e0-4f9a-9f85-2a18136fe81c.png)
You can fix that with enable this permissions: `SEND_MESSAGES` and `EMBED_LINKS`
![image](https://user-images.githubusercontent.com/64538277/152651019-4cadb750-839c-481a-a818-b57cc2356be4.png)
